version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    networks:
      - mynetwork
  